server {
    listen 80;
    sendfile on;
    sendfile_max_chunk 1m;
    client_max_body_size 0;

    location /static/ {
        alias /static_root/;
    }

    location /files/uploadedfiles/ {
        alias /media_root/uploadedfiles/;
    }

    location / {
        proxy_pass http://arches:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}